export const doctors=[
{id:1,name:'Dr. Ananya Sharma',qualification:'MBBS, MD',specialty:'General Physician',experience:8,rating:4.8,fee:299,availability:'Available Now',initials:'AS',color:'blue',languages:'English, Hindi',types:['Video','Audio'],about:'A thoughtful approach to everyday health. Dr. Ananya focuses on listening to your concerns and making the next steps easy to understand.',expertise:['Fever & cold','General wellness','Everyday health concerns']},
{id:2,name:'Dr. Priya Mehta',qualification:'MBBS, MS',specialty:'Gynecologist',experience:10,rating:4.9,fee:499,availability:'Available Today',initials:'PM',color:'rose',languages:'English, Hindi, Gujarati',types:['Video','Audio'],about:'Compassionate support for women through every stage of life, with space to ask questions and talk openly.',expertise:["Women’s health",'Menstrual concerns','Reproductive health']},
{id:3,name:'Dr. Arjun Kapoor',qualification:'MBBS, MD',specialty:'Psychiatrist',experience:7,rating:4.8,fee:399,availability:'Available Now',initials:'AK',color:'violet',languages:'English, Hindi',types:['Video','Audio'],about:'A calm, judgement-free space to talk about mental wellbeing and understand your options.',expertise:['Stress','Anxiety concerns','Mental wellbeing']},
{id:4,name:'Dr. Rahul Verma',qualification:'MBBS, MD',specialty:'General Physician',experience:12,rating:4.7,fee:399,availability:'Available Today',initials:'RV',color:'mint',languages:'English, Hindi, Bengali',types:['Video','Audio'],about:'Patient-centred care for common health concerns, with a clear and practical approach to follow-up.',expertise:['General medicine','Everyday health','Preventive care']}
];
export const findDoctor=id=>doctors.find(d=>d.id===Number(id))||doctors[0];
export const slots=['10:00 AM','10:30 AM','11:15 AM','12:00 PM','01:30 PM','04:00 PM','06:30 PM','07:00 PM'];
export const faqs=[['How does an online consultation work?','Choose a doctor, select video or audio, and book a time that works for you. Enter the waiting room from My Consultations. This website lets you explore the entire journey as a frontend demo.'],['How do I choose a doctor?','Browse by specialty and compare experience, languages, fees and available times. All doctor profiles shown here are illustrative demo data.'],['Can I choose video or audio consultation?','Yes. Select your preferred consultation type before choosing a date and time. Calls on this demo are simulated.'],['How will I receive my prescription?','After a consultation, prescriptions would appear in your account. The demo provides a clearly labelled sample document, without generating treatment.'],['Can I view old prescriptions?','Your demo prescription history is available from My Prescriptions on this browser.'],['How do payments work?','Explore UPI, card and other payment options. No money is charged and no payment information is sent or saved.'],['Can I reschedule my appointment?','Yes. Open an upcoming booking in My Consultations and select Reschedule to choose a new date and time.'],['Is Medergency available on mobile?','This responsive website works on mobile, tablet and desktop.'],['Which languages will be supported?','English is available in this demo. The language settings show the planned Indian-language options.']];
